/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#d9e2fd",
        "surface-tint": "#26dcdd",
        "outline": "#859493",
        "on-secondary-fixed": "#001944",
        "text-secondary": "#94A3B8",
        "primary-container": "#00d2d3",
        "inverse-primary": "#006a6a",
        "secondary-fixed-dim": "#b0c6ff",
        "tertiary-fixed": "#ffdad5",
        "surface-container-lowest": "#040e21",
        "surface-raised": "#10203B",
        "on-primary-fixed": "#002020",
        "surface-deep": "#0B1528",
        "tertiary-container": "#ffa69b",
        "primary-fixed-dim": "#26dcdd",
        "aero-sky": "#0EA5E9",
        "on-tertiary-fixed": "#410002",
        "on-tertiary-container": "#9d000b",
        "surface-container-high": "#202a3e",
        "on-error": "#690005",
        "on-background": "#d9e2fd",
        "on-secondary": "#002d6e",
        "secondary": "#b0c6ff",
        "error-container": "#93000a",
        "surface-dim": "#091326",
        "surface-variant": "#2b3549",
        "chassis-dark": "#070D18",
        "surface-container-low": "#121b2f",
        "border-subtle": "#1E3557",
        "primary": "#48efef",
        "on-primary-fixed-variant": "#004f50",
        "outline-variant": "#3b4949",
        "corsa-red": "#EB2323",
        "background": "#091326",
        "on-secondary-fixed-variant": "#1b448d",
        "error": "#ffb4ab",
        "tertiary": "#ffcdc7",
        "surface-bright": "#30394e",
        "text-muted": "#64748B",
        "warning-amber": "#F59E0B",
        "inverse-surface": "#d9e2fd",
        "text-primary": "#F8FAFC",
        "on-primary-container": "#005556",
        "surface": "#091326",
        "telemetry-emerald": "#10B981",
        "on-surface-variant": "#bacac9",
        "tertiary-fixed-dim": "#ffb4aa",
        "secondary-fixed": "#d9e2ff",
        "surface-container-highest": "#2b3549",
        "surface-container": "#161f33",
        "surface-elevated": "#1A3258",
        "inverse-on-surface": "#273045",
        "on-tertiary-fixed-variant": "#930009",
        "on-tertiary": "#690004",
        "on-secondary-container": "#95b4ff",
        "electric-cyan": "#00D2D3",
        "on-primary": "#003737",
        "on-error-container": "#ffdad6",
        "border-active": "#00D2D3",
        "secondary-container": "#1b448d",
        "primary-fixed": "#56f9f9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "space-4xl": "6rem",
        "gutter-desktop": "2rem",
        "gutter-mobile": "1rem",
        "container-max": "1440px"
      },
      fontFamily: {
        "label-badge": ["JetBrains Mono", "monospace"],
        "label-telemetry": ["JetBrains Mono", "monospace"],
        "display-hero": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-card": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-badge": ["10px", { lineHeight: "12px", letterSpacing: "0.12em", fontWeight: "700" }],
        "label-telemetry": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
        "display-hero": ["72px", { lineHeight: "76px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "title-card": ["18px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-lg": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
